# Generated by Django 4.2.30 on 2026-04-26 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='TeachDetails',
        ),
    ]
