# Generated by Django 4.2.30 on 2026-04-26 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_rename_teacher_teachdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachdetails',
            old_name='Empid',
            new_name='empid',
        ),
    ]
